# @package _global_
defaults:
  - trainer: default.yaml
  - datamodule: data.yaml
  - models: evaluate.yaml
  - logger: wandb.yaml
  - hydra: default.yaml
  - _self_

work_dir: ${hydra:runtime.cwd}
data_dir: ${data_loc}
log_dir: ${work_dir}/${log_loc}

# path to folder with data
data_loc: "~/Documents/GitHub/data"
log_loc: logs

# Additional hyperparams, with dataset chosen in datamodule/data.yaml
seed: 42
source_dataset: null  # Will be dynamically set in run.py
arch: "ClipViTB32"
pretrained: True
base_task: null  # Will be dynamically set in run.py
# num_classes will be automatically determined in run.py

hydra:
  job:
    chdir: false
